# Generated by Django 5.1.5 on 2025-02-14 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
