# Generated by Django 5.1.5 on 2025-02-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_productreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='vendor',
            name='message',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
