# Generated by Django 5.1.5 on 2025-02-25 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_order_price_order_product_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
